M48
; DRILL file KiCad 10.0.3 date 2026-06-15T23:18:06
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-15T23:18:06-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X103.296Y-108.054
X104.125Y-127.81
T2
X106.0Y-140.5
X135.5Y-84.5
X165.5Y-140.5
M30
